[[icedos.hardware.network.samba.shares]]
name = ""
path = ""
comment = ""
browseable = true
readOnly = true
guestOk = false
forceUser = ""
forceGroup = ""
validUsers = []
writeList = []
createMask = "0644"
directoryMask = "0755"

[icedos.hardware.network.samba.shares.extraSettings]
